# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HybridApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HybridApp
  pod 'FlexHybridApp', '0.2.2-1'

end
